# Build Stage
FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
WORKDIR /src

# Copy the solution and project files
COPY ./BusinessOne.sln ./
COPY ./API/API.csproj ./API/
COPY ./Application/Application.csproj ./Application/
COPY ./Infrastructure/Infrastructure.csproj ./Infrastructure/
COPY ./Domain/Domain.csproj ./Domain/
COPY ./Persistence/Persistence.csproj ./Persistence/

# Restore dependencies
RUN dotnet restore

# Copy the entire source code
COPY . .

# Set environment variables for the build process
ENV TokenKey=lWwMN68UKbjuEJAAYq9ke9KYtPrabUTE9kghtxPrysPDfgaezEyfV3gjoA4F90TYcgYRhH5wXC0XhR5idy1n0w==
ENV ASPNETCORE_URLS=http://0.0.0.0:5000;https://0.0.0.0:8444
ENV ASPNETCORE_ENVIRONMENT=Production

# Build and publish the application
RUN dotnet publish ./API/API.csproj -c Release -o /app/

# Runtime Stage
FROM --platform=linux/arm64 mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app

# Copy the published application from the build stage
COPY --from=build-env /app .
COPY API/appsettings.json /app/appsettings.json
COPY API/appsettings.*.json /app/

# Set runtime environment variables to ensure proper binding
ENV ASPNETCORE_URLS=http://0.0.0.0:5000;https://0.0.0.0:8444


# Expose HTTP and HTTPS ports
EXPOSE 5000
EXPOSE 8444

# Run the application
ENTRYPOINT ["dotnet", "API.dll"]
