START TRANSACTION;

ALTER TABLE `PARTY_RELATIONSHIP` ADD `CREATED_BY_USER_LOGIN` varchar(250) CHARACTER SET utf8mb4 NULL;

CREATE INDEX `PARTY_REL_USRLGN` ON `PARTY_RELATIONSHIP` (`CREATED_BY_USER_LOGIN`);

ALTER TABLE `PARTY_RELATIONSHIP` ADD CONSTRAINT `PARTY_REL_USRLGN` FOREIGN KEY (`CREATED_BY_USER_LOGIN`) REFERENCES `USER_LOGIN` (`USER_LOGIN_ID`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20260824080824_AddCreatedByUserLoginToPartyRelationship', '8.0.0');

COMMIT;

