UPDATE SALES_OPPORTUNITY_ROLE SET ROLE_TYPE_ID = 'LEAD' WHERE ROLE_TYPE_ID = 'LEAD_CONTACT';

DELETE pr FROM PARTY_ROLE pr
                   JOIN PARTY_ROLE x ON x.PARTY_ID = pr.PARTY_ID AND x.ROLE_TYPE_ID = 'LEAD'
WHERE pr.ROLE_TYPE_ID = 'LEAD_CONTACT';

UPDATE PARTY p
    JOIN PARTY_ROLE pr ON pr.PARTY_ID = p.PARTY_ID AND pr.ROLE_TYPE_ID = 'LEAD'
SET p.MAIN_ROLE = 'LEAD'
WHERE p.MAIN_ROLE = 'LEAD_CONTACT';    