INSERT INTO SEQUENCE_VALUE_ITEM (SEQ_NAME, SEQ_ID, LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP)
SELECT 'PaymentReceipt', 49999, NOW(), NULL, NOW(), NULL
WHERE NOT EXISTS (
    SELECT 1 FROM SEQUENCE_VALUE_ITEM WHERE SEQ_NAME = 'PaymentReceipt'
);