DELETE FROM INVOICE_ITEM
WHERE INVOICE_ID = 'INV330';

DELETE FROM INVOICE_ROLE
WHERE INVOICE_ID = 'INV330';

DELETE FROM INVOICE_STATUS
WHERE INVOICE_ID = 'INV330';

DELETE ate
FROM ACCTG_TRANS_ENTRY ate
         INNER JOIN ACCTG_TRANS at
                    ON ate.ACCTG_TRANS_ID = at.ACCTG_TRANS_ID
WHERE at.INVOICE_ID = 'INV330';

-- Then delete the transaction header(s)
DELETE FROM ACCTG_TRANS
WHERE INVOICE_ID = 'INV330';

DELETE FROM INVOICE
WHERE INVOICE_ID = 'INV330';

