START TRANSACTION;

DELETE FROM EMPLOYEE_ADVANCE_SCHEDULE
WHERE ADVANCE_ID = '10048';

DELETE FROM EMPLOYEE_ADVANCE
WHERE ADVANCE_ID = '10048'; 

DELETE FROM PAYMENT
WHERE PAYMENT_ID = '14927';



COMMIT;     -- Uncomment to permanently delete
-- ROLLBACK;   -- Uncomment to cancel the deletion