
SET @payment_ids = (
    SELECT GROUP_CONCAT(DISTINCT p.PAYMENT_ID SEPARATOR ',')
    FROM PAYMENT p
             INNER JOIN ORDER_PAYMENT_PREFERENCE opp ON p.PAYMENT_PREFERENCE_ID = opp.ORDER_PAYMENT_PREFERENCE_ID
             INNER JOIN ORDER_HEADER oh ON opp.ORDER_ID = oh.ORDER_ID
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);

-- Step 2: Delete entries
DELETE ate
FROM ACCTG_TRANS_ENTRY ate
         INNER JOIN ACCTG_TRANS at ON ate.ACCTG_TRANS_ID = at.ACCTG_TRANS_ID
WHERE FIND_IN_SET(at.PAYMENT_ID, @payment_ids);

-- Step 3: Delete transactions
DELETE at
FROM ACCTG_TRANS at
WHERE FIND_IN_SET(at.PAYMENT_ID, @payment_ids);

-- Then continue with payment deletion as before

UPDATE FIN_ACCOUNT_TRANS
SET PAYMENT_ID = NULL
WHERE FIN_ACCOUNT_TRANS_ID = '10042'
  AND PAYMENT_ID IS NOT NULL;

-- 1. Payments (linked through ORDER_PAYMENT_PREFERENCE)
DELETE p
FROM PAYMENT p
         INNER JOIN ORDER_PAYMENT_PREFERENCE opp
                    ON p.PAYMENT_PREFERENCE_ID = opp.ORDER_PAYMENT_PREFERENCE_ID
         INNER JOIN ORDER_HEADER oh
                    ON opp.ORDER_ID = oh.ORDER_ID
         INNER JOIN WORK_EFFORT we
                    ON oh.ORDER_ID = we.RELATED_ORDER_ID
WHERE we.CERTIFICATE_NUMBER = '54-0001';

-- 14. Financial Account Transactions (delete after accounting trans, before payments)
DELETE fat
FROM FIN_ACCOUNT_TRANS fat
         INNER JOIN PAYMENT p
                    ON fat.PAYMENT_ID = p.PAYMENT_ID
         INNER JOIN ORDER_PAYMENT_PREFERENCE opp
                    ON p.PAYMENT_PREFERENCE_ID = opp.ORDER_PAYMENT_PREFERENCE_ID
         INNER JOIN ORDER_HEADER oh
                    ON opp.ORDER_ID = oh.ORDER_ID
         INNER JOIN WORK_EFFORT we
                    ON oh.ORDER_ID = we.RELATED_ORDER_ID
WHERE we.CERTIFICATE_NUMBER = 'SITE-0004';




-- 2. Order Payment Preferences
DELETE opp
FROM ORDER_PAYMENT_PREFERENCE opp
         INNER JOIN ORDER_HEADER oh
                    ON opp.ORDER_ID = oh.ORDER_ID
         INNER JOIN WORK_EFFORT we
                    ON oh.ORDER_ID = we.RELATED_ORDER_ID
WHERE we.CERTIFICATE_NUMBER = '54-0001';


-- 3. Order Roles
DELETE FROM ORDER_ROLE
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);


-- 4. Order Statuses
DELETE FROM ORDER_STATUS
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);


-- 5. Order Adjustments
DELETE FROM ORDER_ADJUSTMENT
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);

DELETE FROM ORDER_ITEM_SHIP_GROUP_ASSOC
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we
                        ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);

DELETE FROM ORDER_ITEM_BILLING
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);

DELETE sr
FROM SHIPMENT_RECEIPT sr
         INNER JOIN ORDER_ITEM oi
                    ON sr.ORDER_ID = oi.ORDER_ID
                        AND sr.ORDER_ITEM_SEQ_ID = oi.ORDER_ITEM_SEQ_ID
         INNER JOIN ORDER_HEADER oh
                    ON oi.ORDER_ID = oh.ORDER_ID
         INNER JOIN WORK_EFFORT we
                    ON oh.ORDER_ID = we.RELATED_ORDER_ID
WHERE we.CERTIFICATE_NUMBER = '54-0001';

-- 6. Order Items (critical - many child tables reference this)
DELETE FROM ORDER_ITEM
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);


-- 7. Order Item Ship Groups
DELETE FROM ORDER_ITEM_SHIP_GROUP
WHERE ORDER_ID IN (
    SELECT oh.ORDER_ID
    FROM ORDER_HEADER oh
             INNER JOIN WORK_EFFORT we ON oh.ORDER_ID = we.RELATED_ORDER_ID
    WHERE we.CERTIFICATE_NUMBER = '54-0001'
);

DELETE os
FROM ORDER_SHIPMENT os
         INNER JOIN ORDER_HEADER oh
                    ON os.ORDER_ID = oh.ORDER_ID
         INNER JOIN WORK_EFFORT we
                    ON oh.ORDER_ID = we.RELATED_ORDER_ID
WHERE we.CERTIFICATE_NUMBER = '54-0001';

DELETE FROM ACCTG_TRANS_ENTRY
WHERE ACCTG_TRANS_ID IN (
    SELECT ACCTG_TRANS_ID
    FROM ACCTG_TRANS
    WHERE SHIPMENT_ID = '10519'
);

DELETE FROM ACCTG_TRANS
WHERE SHIPMENT_ID = '10519';

DELETE FROM SHIPMENT_ITEM s
WHERE s.SHIPMENT_ID = '10519';

DELETE FROM SHIPMENT_STATUS s
WHERE s.SHIPMENT_ID = '10519';

DELETE FROM SHIPMENT_ROUTE_SEGMENT s
WHERE s.SHIPMENT_ID = '10519';

DELETE FROM SHIPMENT s
WHERE s.PRIMARY_ORDER_ID = 'PO10699';

UPDATE WORK_EFFORT
SET RELATED_ORDER_ID = NULL
WHERE CERTIFICATE_NUMBER = '54-0001';

-- 9. Order Header (after all its children)
DELETE oh
FROM ORDER_HEADER oh
         INNER JOIN WORK_EFFORT we
                    ON oh.ORDER_ID = we.RELATED_ORDER_ID
WHERE we.CERTIFICATE_NUMBER = '54-0001';


-- 10. Certificate line items (child WorkEfforts)
DELETE child
FROM WORK_EFFORT AS child
         INNER JOIN WORK_EFFORT AS parent
                    ON child.WORK_EFFORT_PARENT_ID = parent.WORK_EFFORT_ID
WHERE parent.CERTIFICATE_NUMBER = '54-0001';

DELETE FROM INVENTORY_ITEM_DETAIL
WHERE INVENTORY_ITEM_ID IN (
    SELECT t.INVENTORY_ITEM_ID
    FROM (
             SELECT INVENTORY_ITEM_ID
             FROM INVENTORY_ITEM_DETAIL
             WHERE WORK_EFFORT_ID = '10122'
         ) AS t
);


DELETE FROM INVENTORY_ITEM
WHERE INVENTORY_ITEM_ID = '10122';

DELETE FROM ACCTG_TRANS_ENTRY
WHERE ACCTG_TRANS_ID IN (
    SELECT ACCTG_TRANS_ID
    FROM ACCTG_TRANS
    WHERE WORK_EFFORT_ID = '10122'
);

DELETE FROM ACCTG_TRANS
WHERE WORK_EFFORT_ID = '10122';

-- 11. Certificate header
DELETE FROM WORK_EFFORT
WHERE CERTIFICATE_NUMBER = '54-0001';