SET @srId = '10756';

DELETE ate
FROM ACCTG_TRANS_ENTRY ate
         INNER JOIN ACCTG_TRANS at ON ate.ACCTG_TRANS_ID = at.ACCTG_TRANS_ID
WHERE at.SALES_REQUEST_ID = @srId;

DELETE FROM ACCTG_TRANS WHERE SALES_REQUEST_ID = @srId;

UPDATE PAYMENT p
SET p.FIN_ACCOUNT_TRANS_ID = NULL
WHERE p.SALES_REQUEST_ID = :salesRequestId
  AND p.FIN_ACCOUNT_TRANS_ID IS NOT NULL;

DELETE fat
FROM FIN_ACCOUNT_TRANS fat
         INNER JOIN PAYMENT p ON fat.PAYMENT_ID = p.PAYMENT_ID
WHERE p.SALES_REQUEST_ID = @srId;

DELETE FROM PAYMENT WHERE SALES_REQUEST_ID = @srId;

DELETE FROM SALES_REQUEST_INSTALLMENT
WHERE SALES_REQUEST_ID = :salesRequestId;

DELETE FROM SALES_REQUEST WHERE SALES_REQUEST_ID = @srId;