DROP VIEW IF EXISTS Dim_CustomTimePeriod;

CREATE VIEW Dim_CustomTimePeriod AS
SELECT
    CUSTOM_TIME_PERIOD_ID,
    PERIOD_TYPE_ID,
    PERIOD_NAME,
    FROM_DATE,
    THRU_DATE

FROM CUSTOM_TIME_PERIOD

WHERE PERIOD_TYPE_ID IN ('FISCAL_YEAR', 'FISCAL_QUARTER')

ORDER BY FROM_DATE;
