-- ============================================================================
-- Corrects INVENTORY (material issuance to site) postings mis-generated by
-- GeneralLedgerService.CreateAcctgTransForCertificateIssuance.
--
-- Bug: the method looked its certificate line up by ProductId + QuantityUomId
-- and posted the WHOLE line total. When two lines of a certificate shared a
-- product+UOM, FirstOrDefault returned the same line for every inventory
-- deduction -- so one line was posted N times and the other never at all.
--
-- Affected: GL 124426 only (all 11 other project accounts reconcile exactly).
--   4 certificates, net overstatement 286,690.00 on 124426,
--   with GL 140000 (مخزون) over-credited by the same amount.
--
-- Code fix that stops this recurring:
--   GeneralLedgerService.CreateAcctgTransForCertificateIssuance -- now takes the
--     certificate line id + issued quantity, posts issuedQuantity * line rate.
--   ProjectService.IssueMaterialsForCertificate -- passes both.
--
-- STATUS
--   localhost   APPLIED 2026-07-28. Verified after commit: GL 124426 = 3,079,668.06,
--               0 orphan entries, 0 unbalanced transactions, 0 residual variance
--               across all 12 project accounts.
--   production  NOT APPLIED. Re-run the BEFORE query there first and confirm the
--               same four certificates (and no others) show a variance.
--
-- NOT covered by this script: GL 140000 (مخزون) still carries a separate break of
-- roughly -324,543 against 35,000 of stock on hand -- receipts value goods into
-- inventory below the procurement certificates they came from. Different defect.
--
-- Strategy: repoint each surplus transaction onto the certificate line that was
-- never posted, and delete what remains. No new ACCTG_TRANS ids are minted, so
-- the AcctgTrans sequence is untouched. Amounts and descriptions are derived
-- from the certificate line itself -- nothing is hardcoded. Re-running the
-- script is safe: every statement is idempotent.
--
-- REVIEW BEFORE RUNNING. Take a backup first:
--   mysqldump erp_contracts ACCTG_TRANS ACCTG_TRANS_ENTRY \
--     > backup_before_issuance_fix.sql
-- ============================================================================

START TRANSACTION;

-- ---------------------------------------------------------------------------
-- BEFORE: expect 4 rows, variance +286,690.00 in total
-- ---------------------------------------------------------------------------
SELECT 'BEFORE' phase, act.WORK_EFFORT_ID cert, we.CERTIFICATE_NUMBER,
       ROUND(SUM(ate.AMOUNT), 2) posted,
       (SELECT ROUND(SUM(ci.QUANTITY * ci.RATE), 2) FROM WORK_EFFORT ci
         WHERE ci.WORK_EFFORT_PARENT_ID = act.WORK_EFFORT_ID
           AND ci.WORK_EFFORT_TYPE_ID = 'CERTIFICATE_ITEM') correct
FROM ACCTG_TRANS act
JOIN ACCTG_TRANS_ENTRY ate ON ate.ACCTG_TRANS_ID = act.ACCTG_TRANS_ID
                          AND ate.GL_ACCOUNT_ID = '124426'
JOIN WORK_EFFORT we ON we.WORK_EFFORT_ID = act.WORK_EFFORT_ID
WHERE act.ACCTG_TRANS_TYPE_ID = 'INVENTORY'
  AND act.WORK_EFFORT_ID IN ('16132', '16362', '17139', '17473')
GROUP BY 1, 2, 3;

-- ---------------------------------------------------------------------------
-- STEP 1 -- repoint the 4 surplus transactions onto the omitted lines.
--
--   trans   cert    was posted as              becomes (certificate line)
--   16590   16132   نقل            1,100.00 -> 16137  اكراميات            90.00
--   16693   16362   خرسانه       130,000.00 -> 16364  خرسانه غرفه المحول 10,400.00
--   17604   17139   نقل اسمنت      1,500.00 -> 17146  عتب مباني        1,920.00
--   18265   17473   شكاره رخام    10,000.00 -> 17475  شكاره زلط         3,500.00
--
-- Both entries (debit 124426 / credit 140000) of each transaction are updated,
-- so the pair stays balanced.
-- ---------------------------------------------------------------------------

UPDATE ACCTG_TRANS_ENTRY ate
  JOIN WORK_EFFORT ci ON ci.WORK_EFFORT_ID = '16137'
   SET ate.AMOUNT             = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.ORIG_AMOUNT        = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.DESCRIPTION        = ci.DESCRIPTION,
       ate.PRODUCT_ID         = ci.PRODUCT_ID,
       ate.LAST_UPDATED_STAMP = NOW()
 WHERE ate.ACCTG_TRANS_ID = '16590';

UPDATE ACCTG_TRANS_ENTRY ate
  JOIN WORK_EFFORT ci ON ci.WORK_EFFORT_ID = '16364'
   SET ate.AMOUNT             = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.ORIG_AMOUNT        = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.DESCRIPTION        = ci.DESCRIPTION,
       ate.PRODUCT_ID         = ci.PRODUCT_ID,
       ate.LAST_UPDATED_STAMP = NOW()
 WHERE ate.ACCTG_TRANS_ID = '16693';

UPDATE ACCTG_TRANS_ENTRY ate
  JOIN WORK_EFFORT ci ON ci.WORK_EFFORT_ID = '17146'
   SET ate.AMOUNT             = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.ORIG_AMOUNT        = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.DESCRIPTION        = ci.DESCRIPTION,
       ate.PRODUCT_ID         = ci.PRODUCT_ID,
       ate.LAST_UPDATED_STAMP = NOW()
 WHERE ate.ACCTG_TRANS_ID = '17604';

UPDATE ACCTG_TRANS_ENTRY ate
  JOIN WORK_EFFORT ci ON ci.WORK_EFFORT_ID = '17475'
   SET ate.AMOUNT             = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.ORIG_AMOUNT        = ROUND(ci.QUANTITY * ci.RATE, 2),
       ate.DESCRIPTION        = ci.DESCRIPTION,
       ate.PRODUCT_ID         = ci.PRODUCT_ID,
       ate.LAST_UPDATED_STAMP = NOW()
 WHERE ate.ACCTG_TRANS_ID = '18265';

-- ---------------------------------------------------------------------------
-- STEP 2 -- delete the 4 transactions that have no certificate line at all.
--   16695 (cert 16362, 130,000.00)
--   18267, 18269, 18271 (cert 17473, 10,000.00 each)
-- Verified: 0 rows in GL_RECONCILIATION_ENTRY and 0 in ACCTG_TRANS_ATTRIBUTE
-- reference these ids.
-- ---------------------------------------------------------------------------

DELETE FROM ACCTG_TRANS_ENTRY WHERE ACCTG_TRANS_ID IN ('16695', '18267', '18269', '18271');
DELETE FROM ACCTG_TRANS       WHERE ACCTG_TRANS_ID IN ('16695', '18267', '18269', '18271');

-- ---------------------------------------------------------------------------
-- No Power BI step needed: fact_gl_transactions is a VIEW over ACCTG_TRANS +
-- ACCTG_TRANS_ENTRY (not a materialized table), so it follows the base tables
-- automatically. Nothing else in the schema references these ACCTG_TRANS ids.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- STEP 3 (optional) -- clear the sub-cent rounding tails left by the 4-decimal
-- landed-cost unit price in ReceiveInventoryFromPurchaseOrder.cs:258. The code
-- fix rounds at ledger scale going forward; these two are the existing ones.
--   16729 -> 32,799.999 becomes 32,800.00  (GL 124426, this account)
--   18616 -> 11,436.371 becomes 11,436.37  (GL 124422, different project)
-- ---------------------------------------------------------------------------

UPDATE ACCTG_TRANS_ENTRY ate
  JOIN ACCTG_TRANS act ON act.ACCTG_TRANS_ID = ate.ACCTG_TRANS_ID
   SET ate.AMOUNT      = ROUND(ate.AMOUNT, 2),
       ate.ORIG_AMOUNT = ROUND(ate.ORIG_AMOUNT, 2)
 WHERE act.ACCTG_TRANS_TYPE_ID = 'INVENTORY'
   AND act.IS_POSTED = 'Y'
   AND ate.AMOUNT <> ROUND(ate.AMOUNT, 2);

-- ---------------------------------------------------------------------------
-- AFTER: every certificate must now show posted = correct.
-- Expected: 16132 -> 131,100.00 | 16362 -> 140,400.00
--           17139 ->  87,400.00 | 17473 ->  23,000.00
-- ---------------------------------------------------------------------------
SELECT 'AFTER' phase, act.WORK_EFFORT_ID cert, we.CERTIFICATE_NUMBER,
       ROUND(SUM(ate.AMOUNT), 2) posted,
       (SELECT ROUND(SUM(ci.QUANTITY * ci.RATE), 2) FROM WORK_EFFORT ci
         WHERE ci.WORK_EFFORT_PARENT_ID = act.WORK_EFFORT_ID
           AND ci.WORK_EFFORT_TYPE_ID = 'CERTIFICATE_ITEM') correct
FROM ACCTG_TRANS act
JOIN ACCTG_TRANS_ENTRY ate ON ate.ACCTG_TRANS_ID = act.ACCTG_TRANS_ID
                          AND ate.GL_ACCOUNT_ID = '124426'
JOIN WORK_EFFORT we ON we.WORK_EFFORT_ID = act.WORK_EFFORT_ID
WHERE act.ACCTG_TRANS_TYPE_ID = 'INVENTORY'
  AND act.WORK_EFFORT_ID IN ('16132', '16362', '17139', '17473')
GROUP BY 1, 2, 3;

-- Whole-account check across all 12 project accounts -- expect ZERO rows.
SELECT 'STILL BROKEN' flag, t.GL_ACCOUNT_ID, t.WORK_EFFORT_ID,
       ROUND(t.posted, 2) posted, ROUND(t.correct, 2) correct
FROM (
  SELECT act.WORK_EFFORT_ID, ate.GL_ACCOUNT_ID, SUM(ate.AMOUNT) posted,
         (SELECT SUM(ci.QUANTITY * ci.RATE) FROM WORK_EFFORT ci
           WHERE ci.WORK_EFFORT_PARENT_ID = act.WORK_EFFORT_ID
             AND ci.WORK_EFFORT_TYPE_ID = 'CERTIFICATE_ITEM') correct
  FROM ACCTG_TRANS act
  JOIN ACCTG_TRANS_ENTRY ate ON ate.ACCTG_TRANS_ID = act.ACCTG_TRANS_ID
                            AND ate.DEBIT_CREDIT_FLAG = 'D'
  WHERE act.ACCTG_TRANS_TYPE_ID = 'INVENTORY' AND act.IS_POSTED = 'Y'
  GROUP BY act.WORK_EFFORT_ID, ate.GL_ACCOUNT_ID
) t
WHERE ABS(t.posted - COALESCE(t.correct, 0)) > 0.01;

-- Debits must still equal credits on every touched transaction -- expect ZERO rows.
SELECT 'UNBALANCED' flag, ACCTG_TRANS_ID,
       SUM(CASE WHEN DEBIT_CREDIT_FLAG = 'D' THEN AMOUNT ELSE -AMOUNT END) diff
FROM ACCTG_TRANS_ENTRY
WHERE ACCTG_TRANS_ID IN ('16590', '16693', '17604', '18265')
GROUP BY ACCTG_TRANS_ID
HAVING ABS(diff) > 0.001;

-- Final GL 124426 balance -- expect 3,079,668.06 (was 3,366,358.059).
SELECT 'GL 124426 ending balance' label,
       ROUND(SUM(CASE WHEN ate.DEBIT_CREDIT_FLAG = 'D' THEN ate.AMOUNT ELSE -ate.AMOUNT END), 2) balance
FROM ACCTG_TRANS act
JOIN ACCTG_TRANS_ENTRY ate ON ate.ACCTG_TRANS_ID = act.ACCTG_TRANS_ID
                          AND ate.GL_ACCOUNT_ID = '124426'
WHERE act.IS_POSTED = 'Y' AND act.GL_FISCAL_TYPE_ID = 'ACTUAL';

-- ============================================================================
-- Review the output above, then run ONE of:
COMMIT;
--   ROLLBACK;
-- ============================================================================
