START TRANSACTION;

ALTER TABLE `PARTY_RELATIONSHIP` DROP FOREIGN KEY `PARTY_REL_USRLGN`;

ALTER TABLE `SALES_OPPORTUNITY` DROP FOREIGN KEY `SLSOPP_USRLGN`;

ALTER TABLE `SALES_OPPORTUNITY_ACTION` DROP FOREIGN KEY `SLSOPPACT_USRLGN`;

ALTER TABLE `SALES_OPPORTUNITY_HISTORY` DROP FOREIGN KEY `SLOPHI_USRLGN`;

ALTER TABLE `SALES_OPPORTUNITY_HISTORY` MODIFY COLUMN `MODIFIED_BY_USER_LOGIN` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `SALES_OPPORTUNITY_ACTION` MODIFY COLUMN `CREATED_BY_USER_LOGIN` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `SALES_OPPORTUNITY` MODIFY COLUMN `CREATED_BY_USER_LOGIN` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `PARTY_RELATIONSHIP` MODIFY COLUMN `CREATED_BY_USER_LOGIN` varchar(255) CHARACTER SET utf8mb4 NULL;

ALTER TABLE `PARTY_RELATIONSHIP` ADD CONSTRAINT `PARTY_REL_CREATED_BY_USER` FOREIGN KEY (`CREATED_BY_USER_LOGIN`) REFERENCES `AspNetUsers` (`Id`);

ALTER TABLE `SALES_OPPORTUNITY` ADD CONSTRAINT `SLSOPP_CREATED_BY_USER` FOREIGN KEY (`CREATED_BY_USER_LOGIN`) REFERENCES `AspNetUsers` (`Id`);

ALTER TABLE `SALES_OPPORTUNITY_ACTION` ADD CONSTRAINT `SLSOPPACT_CREATED_BY_USER` FOREIGN KEY (`CREATED_BY_USER_LOGIN`) REFERENCES `AspNetUsers` (`Id`);

ALTER TABLE `SALES_OPPORTUNITY_HISTORY` ADD CONSTRAINT `SLOPHI_MODIFIED_BY_USER` FOREIGN KEY (`MODIFIED_BY_USER_LOGIN`) REFERENCES `AspNetUsers` (`Id`);

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20260824094531_RepointActorColumnsToAspNetUsers', '8.0.0');

COMMIT;

