
DELETE FROM INVOICE_STATUS
WHERE STATUS_ID <> 'INVOICE_IN_PROCESS'
  AND INVOICE_ID = 'INV39';

DELETE ate
FROM ACCTG_TRANS_ENTRY ate
         INNER JOIN ACCTG_TRANS at
                    ON ate.ACCTG_TRANS_ID = at.ACCTG_TRANS_ID
WHERE at.INVOICE_ID = 'INV39';

-- Then delete the transaction header(s)
DELETE FROM ACCTG_TRANS
WHERE INVOICE_ID = 'INV39';

UPDATE INVOICE
SET STATUS_ID = 'INVOICE_IN_PROCESS'
WHERE INVOICE_ID = 'INV39';


