-- =============================================================================
-- SORT_ORDER UPDATE STATEMENTS
-- Logic: numbers follow the natural reading order of financial statements
--   P&L: Revenue → Cost of Sales → Gross Profit → OpEx → EBIT → Interest → Tax → Net
--   B/S: Assets (Current → Non-Current) → Liabilities (Current → LT) → Equity
-- Gap of 10 between values leaves room to insert new items without renumbering
-- =============================================================================
-- PREREQUISITE: Add SORT_ORDER column to each FK table if not already present
-- =============================================================================

/*ALTER TABLE GL_REPORT               ADD COLUMN IF NOT EXISTS SORT_ORDER INT NULL;
ALTER TABLE GL_CLASS_COURSE         ADD COLUMN IF NOT EXISTS SORT_ORDER INT NULL;
ALTER TABLE GL_SUB_CLASS            ADD COLUMN IF NOT EXISTS SORT_ORDER INT NULL;
ALTER TABLE GL_SUB_CLASS_2          ADD COLUMN IF NOT EXISTS SORT_ORDER INT NULL;
ALTER TABLE GL_ACCOUNT_COURSE_LABEL ADD COLUMN IF NOT EXISTS SORT_ORDER INT NULL;
ALTER TABLE GL_SUB_ACCOUNT_COURSE_LABEL ADD COLUMN IF NOT EXISTS SORT_ORDER INT NULL;*/

-- =============================================================================
-- GL_REPORT  (2 values)
-- Balance Sheet always shown first, P&L second — standard presentation
-- =============================================================================

UPDATE GL_REPORT SET SORT_ORDER = 10 WHERE GL_REPORT_ID = 'BALANCE_SHEET';
UPDATE GL_REPORT SET SORT_ORDER = 20 WHERE GL_REPORT_ID = 'PROFIT_AND_LOSS';

-- =============================================================================
-- GL_CLASS_COURSE  (7 values)
-- B/S side first (Assets → Liabilities & Equity), then P&L waterfall
-- =============================================================================

-- Balance Sheet
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 10  WHERE GL_CLASS_COURSE_ID = 'ASSETS';
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 20  WHERE GL_CLASS_COURSE_ID = 'LIABILITIES_AND_OWNERS_EQUITY';

-- P&L waterfall top to bottom
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 30  WHERE GL_CLASS_COURSE_ID = 'TRADING_ACCOUNT';
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 40  WHERE GL_CLASS_COURSE_ID = 'OPERATING_ACCOUNT';
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 50  WHERE GL_CLASS_COURSE_ID = 'NON_OPERATING';
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 60  WHERE GL_CLASS_COURSE_ID = 'INTEREST_AND_TAX';

-- Adjusting entries always last
UPDATE GL_CLASS_COURSE SET SORT_ORDER = 90  WHERE GL_CLASS_COURSE_ID = 'ADJUSTING';

-- =============================================================================
-- GL_SUB_CLASS  (14 values)
-- =============================================================================

-- Balance Sheet — Assets side
UPDATE GL_SUB_CLASS SET SORT_ORDER = 10  WHERE GL_SUB_CLASS_ID = 'ASSETS';

-- Balance Sheet — Liabilities & Equity side
UPDATE GL_SUB_CLASS SET SORT_ORDER = 20  WHERE GL_SUB_CLASS_ID = 'LIABILITIES';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 30  WHERE GL_SUB_CLASS_ID = 'OWNERS_EQUITY';

-- P&L — Trading account (Gross Profit block)
UPDATE GL_SUB_CLASS SET SORT_ORDER = 40  WHERE GL_SUB_CLASS_ID = 'SALES';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 50  WHERE GL_SUB_CLASS_ID = 'COST_OF_SALES';

-- P&L — Operating account (EBITDA / EBIT block)
UPDATE GL_SUB_CLASS SET SORT_ORDER = 60  WHERE GL_SUB_CLASS_ID = 'OPERATING_EXPENSES';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 70  WHERE GL_SUB_CLASS_ID = 'DEPRECIATION_AND_AMORTIZATION';

-- P&L — Non-operating
UPDATE GL_SUB_CLASS SET SORT_ORDER = 80  WHERE GL_SUB_CLASS_ID = 'INTEREST_INCOME';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 90  WHERE GL_SUB_CLASS_ID = 'DIVIDEND_INCOME';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 100 WHERE GL_SUB_CLASS_ID = 'GAIN_LOSS_ON_SALES_OF_ASSET';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 110 WHERE GL_SUB_CLASS_ID = 'EXCHANGE_LOSS_GAIN';

-- P&L — Interest & Tax (below operating profit)
UPDATE GL_SUB_CLASS SET SORT_ORDER = 120 WHERE GL_SUB_CLASS_ID = 'INTEREST_EXPENSE';
UPDATE GL_SUB_CLASS SET SORT_ORDER = 130 WHERE GL_SUB_CLASS_ID = 'TAXATION';

-- Adjusting
UPDATE GL_SUB_CLASS SET SORT_ORDER = 140 WHERE GL_SUB_CLASS_ID = 'ADJUSTING';

-- =============================================================================
-- GL_SUB_CLASS_2  (22 values)
-- =============================================================================

-- Balance Sheet — Current Assets first, then Non-Current
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 10  WHERE GL_SUB_CLASS_2_ID = 'CURRENT_ASSETS';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 20  WHERE GL_SUB_CLASS_2_ID = 'NON_CURRENT_ASSETS';

-- Balance Sheet — Current Liabilities, then Long Term, then Equity
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 30  WHERE GL_SUB_CLASS_2_ID = 'CURRENT_LIABILITIES';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 40  WHERE GL_SUB_CLASS_2_ID = 'LONG_TERM_LIABILITIES';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 50  WHERE GL_SUB_CLASS_2_ID = 'SHARE_CAPITAL';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 60  WHERE GL_SUB_CLASS_2_ID = 'SHARE_PREMIUM';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 70  WHERE GL_SUB_CLASS_2_ID = 'RETAINED_EARNINGS';

-- P&L — mirrors SubClass waterfall at finer grain
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 80  WHERE GL_SUB_CLASS_2_ID = 'SALES';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 90  WHERE GL_SUB_CLASS_2_ID = 'COST_OF_SALES';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 100 WHERE GL_SUB_CLASS_2_ID = 'ADMINISTRATION';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 110 WHERE GL_SUB_CLASS_2_ID = 'SALES_AND_DISTRIBUTION';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 120 WHERE GL_SUB_CLASS_2_ID = 'MARKETING';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 130 WHERE GL_SUB_CLASS_2_ID = 'DEPRECIATION';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 140 WHERE GL_SUB_CLASS_2_ID = 'AMORTIZATION';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 150 WHERE GL_SUB_CLASS_2_ID = 'INTEREST_INCOME';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 160 WHERE GL_SUB_CLASS_2_ID = 'DIVIDEND_INCOME';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 170 WHERE GL_SUB_CLASS_2_ID = 'GAIN_LOSS_ON_SALES_OF_ASSET';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 180 WHERE GL_SUB_CLASS_2_ID = 'EXCHANGE_LOSS_GAIN';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 190 WHERE GL_SUB_CLASS_2_ID = 'FINANCIAL_EXPENSES';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 200 WHERE GL_SUB_CLASS_2_ID = 'INTEREST_EXPENSE';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 210 WHERE GL_SUB_CLASS_2_ID = 'TAXATION';
UPDATE GL_SUB_CLASS_2 SET SORT_ORDER = 220 WHERE GL_SUB_CLASS_2_ID = 'ADJUSTING';

-- =============================================================================
-- GL_ACCOUNT_COURSE_LABEL  (47 values)
-- Grouped by B/S section first, then P&L section
-- Within each section: most liquid / most significant first
-- =============================================================================

-- ── Balance Sheet: Current Assets ────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 10  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'CASH_AND_CASH_EQUIVALENTS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 20  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'RECEIVABLES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 30  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INVENTORY';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 40  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INVENTORY_LANDS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 50  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'OTHER_CURRENT_ASSETS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 60  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'CURRENT_INSTALLMENTS_OF_LT_DEBT';

-- ── Balance Sheet: Non-Current Assets ────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 70  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'PROPERTY_PLANT_AND_EQUIPMENT';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 80  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'EQUIPMENT';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 90  WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'FURNITURE_AND_FIXTURES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 100 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'VEHICLES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 110 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INTANGIBLE_ASSETS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 120 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INVESTMENTS';

-- ── Balance Sheet: Current Liabilities ───────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 130 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'TRADE_PAYABLES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 140 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'OTHER_PAYABLES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 150 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'PAYABLES_LANDS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 160 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'PAYABLES_STOCKS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 170 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'OTHER_CURRENT_LIABILITIES';

-- ── Balance Sheet: Long Term Liabilities ─────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 180 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'LONG_TERM_OBLIGATIONS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 190 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'OTHER_LONG_TERM_LIABILITIES';

-- ── Balance Sheet: Equity ─────────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 200 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'SHARE_CAPITAL';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 210 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'SHARE_PREMIUM';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 220 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'RETAINED_EARNINGS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 230 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'DIVIDENDS_PAID';

-- ── P&L: Revenue ──────────────────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 240 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'SALES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 250 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'SALES_RETURN';

-- ── P&L: Cost of Sales ────────────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 260 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'COST_OF_SALES';

-- ── P&L: Operating Expenses ───────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 270 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'STAFF_COSTS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 280 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'RENT';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 290 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'UTILITIES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 300 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INTERNET_AND_TELECOM';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 310 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'TELEPHONE';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 320 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'ADVERTISEMENTS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 330 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'COMMISSIONS';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 340 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'PROFESSIONAL_SERVICES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 350 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'OFFICE_SUPPLIES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 360 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'ENTERTAINMENT';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 370 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'TRAVEL';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 380 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'CONFERENCES';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 390 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'BAD_DEBT_EXPENSE';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 400 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'OTHER_EXPENSES';

-- ── P&L: Depreciation ─────────────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 410 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'AMORTIZATION_OF_INTANGIBLE_ASSETS';

-- ── P&L: Non-Operating ────────────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 420 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INTEREST_INCOME';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 430 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'DIVIDEND_INCOME';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 440 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'GAIN_LOSS_ON_SALES_OF_ASSET';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 450 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'EXCHANGE_LOSS_GAIN';

-- ── P&L: Interest & Tax ───────────────────────────────────────────────────────
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 460 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'INTEREST_EXPENSE';
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 470 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'TAXATION';

-- Adjusting
UPDATE GL_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 480 WHERE GL_ACCOUNT_COURSE_LABEL_ID = 'ADJUSTING';

-- =============================================================================
-- GL_SUB_ACCOUNT_COURSE_LABEL  (46 values)
-- Grouped to mirror the Account level ordering above
-- =============================================================================

-- ── Current Assets ────────────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 10  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Cash at Bank';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 20  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Cash in Hand';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 30  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Owners Cash';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 40  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Trade Receivables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 50  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Project Receivables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 60  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Rent Receivables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 70  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Staff Receivables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 80  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Credit Card Transit';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 90  WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'WIP Own Projects';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 100 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'WIP Third Party';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 110 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Units for Sale';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 120 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Materials Inventory';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 130 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Land Inventory';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 140 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Other Receivables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 150 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Permanent Advances';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 160 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Other Current Assets';

-- ── Non-Current Assets ────────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 170 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Property Plant Equipment';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 180 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Accumulated Depreciation';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 190 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Vehicles';

-- ── Current Liabilities ───────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 200 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Trade Payables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 210 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Accrued Expenses';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 220 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Tax Payables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 230 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Customer Credits';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 240 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Subcontractor Payables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 250 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Project Partnerships';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 260 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Rental Partnerships';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 270 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Temp Partnerships';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 280 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Land Owner Payables';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 290 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Other Payables';

-- ── Long Term Liabilities ─────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 300 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Long Term Obligations';

-- ── Equity ────────────────────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 310 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Share Capital';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 320 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Partner Current Accounts';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 330 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Retained Earnings';

-- ── P&L: Revenue ──────────────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 340 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Sales';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 350 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Sales Return';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 360 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Interest Income';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 370 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Dividend Income';

-- ── P&L: Expenses ─────────────────────────────────────────────────────────────
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 380 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Cost of Sales';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 390 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Staff Costs';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 400 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Rent Expense';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 410 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Utilities';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 420 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Internet and Telecom';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 430 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Advertisements';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 440 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Depreciation Expense';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 450 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Other Expenses';
UPDATE GL_SUB_ACCOUNT_COURSE_LABEL SET SORT_ORDER = 460 WHERE GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'Interest Expense';

-- =============================================================================
-- VERIFICATION — check any NULL sort orders after running
-- =============================================================================

-- SELECT 'GL_REPORT'               AS TBL, GL_REPORT_ID               AS ID, SORT_ORDER FROM GL_REPORT               WHERE SORT_ORDER IS NULL
-- UNION ALL
-- SELECT 'GL_CLASS_COURSE'         AS TBL, GL_CLASS_COURSE_ID         AS ID, SORT_ORDER FROM GL_CLASS_COURSE         WHERE SORT_ORDER IS NULL
-- UNION ALL
-- SELECT 'GL_SUB_CLASS'            AS TBL, GL_SUB_CLASS_ID            AS ID, SORT_ORDER FROM GL_SUB_CLASS            WHERE SORT_ORDER IS NULL
-- UNION ALL
-- SELECT 'GL_SUB_CLASS_2'          AS TBL, GL_SUB_CLASS_2_ID          AS ID, SORT_ORDER FROM GL_SUB_CLASS_2          WHERE SORT_ORDER IS NULL
-- UNION ALL
-- SELECT 'GL_ACCOUNT_COURSE_LABEL' AS TBL, GL_ACCOUNT_COURSE_LABEL_ID AS ID, SORT_ORDER FROM GL_ACCOUNT_COURSE_LABEL WHERE SORT_ORDER IS NULL
-- UNION ALL
-- SELECT 'GL_SUB_ACCOUNT'          AS TBL, GL_SUB_ACCOUNT_COURSE_LABEL_ID AS ID, SORT_ORDER FROM GL_SUB_ACCOUNT_COURSE_LABEL WHERE SORT_ORDER IS NULL;

