-- Translate ABBREVIATION to Arabic for the 23 UOMs from the client's uom.xlsx sheet
-- (SORT_ORDER 10-230). Only the ones that were still Latin need changing here --
-- the trip/lump-sum/errand/cart/phase abbreviations were already Arabic. Idempotent.

UPDATE UOM SET ABBREVIATION = 'م', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'LN_m';
UPDATE UOM SET ABBREVIATION = 'م2', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'AR_m2';
UPDATE UOM SET ABBREVIATION = 'م3', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'VL_m3';
UPDATE UOM SET ABBREVIATION = 'م.ط', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'LN_m_linear';
UPDATE UOM SET ABBREVIATION = 'ش', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'WT_shikara';
UPDATE UOM SET ABBREVIATION = 'طن', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'WT_t';
UPDATE UOM SET ABBREVIATION = 'برميل', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'VL_bbl';
UPDATE UOM SET ABBREVIATION = 'لتر', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'VL_l';
UPDATE UOM SET ABBREVIATION = 'مرحلة', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'CUST_phase';
UPDATE UOM SET ABBREVIATION = 'م.ط/2', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'LN_m_half';
UPDATE UOM SET ABBREVIATION = 'م.ط × 2', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'LN_m_2x';
UPDATE UOM SET ABBREVIATION = 'م2 × 1.5', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'AR_m2_1.5x';
UPDATE UOM SET ABBREVIATION = 'م.ط × 1.5', LAST_UPDATED_STAMP = NOW(), LAST_UPDATED_TX_STAMP = NOW() WHERE UOM_ID = 'LN_m_1.5x';
