SELECT
    ga.GL_ACCOUNT_ID,
    ga.GL_ACCOUNT_TYPE_ID,
    ga.GL_ACCOUNT_CLASS_ID,
    ga.PARENT_GL_ACCOUNT_ID,
    ga.ACCOUNT_CODE,
    ga.ACCOUNT_NAME,
    ga.DESCRIPTION,
    ga.ACCOUNT_NAME_ARABIC,
    gao.ORGANIZATION_PARTY_ID
FROM
    GL_ACCOUNT ga
        INNER JOIN
    GL_ACCOUNT_ORGANIZATION gao
    ON
            ga.GL_ACCOUNT_ID = gao.GL_ACCOUNT_ID
where ga.GL_ACCOUNT_CLASS_ID = 'CASH_EQUIVALENT'
ORDER BY
    ga.GL_ACCOUNT_ID, gao.ORGANIZATION_PARTY_ID;