INSERT INTO PAYMENT_METHOD
(PAYMENT_METHOD_ID, PAYMENT_METHOD_TYPE_ID, PARTY_ID, GL_ACCOUNT_ID, FIN_ACCOUNT_ID,
 DESCRIPTION, FROM_DATE, THRU_DATE,
 LAST_UPDATED_STAMP, LAST_UPDATED_TX_STAMP, CREATED_STAMP, CREATED_TX_STAMP)
SELECT 'CURRENT_YASSER_SAUDI_SAWA', 'FIN_ACCOUNT', 'Company', '250284', NULL,
       'ياسر سعودي جاري مشروع سوا', '2026-10-01 00:00:00', NULL,
       NOW(), NOW(), NOW(), NOW()
FROM DUAL
WHERE EXISTS     (SELECT 1 FROM GL_ACCOUNT     WHERE GL_ACCOUNT_ID = '250284')
  AND NOT EXISTS (SELECT 1 FROM PAYMENT_METHOD WHERE PAYMENT_METHOD_ID = 'CURRENT_YASSER_SAUDI_SAWA'
                                                  OR GL_ACCOUNT_ID = '250284');    