SELECT
    we_item.WORK_EFFORT_ID,
    we_item.GlAccountId,
    p.WORK_EFFORT_ID AS project_id_to_set,
    p.PROJECT_NAME
FROM WORK_EFFORT we_item
         INNER JOIN WORK_EFFORT p ON we_item.GlAccountId = p.GlAccountId
WHERE we_item.WORK_EFFORT_TYPE_ID = 'PAYMENT_CERTIFICATE_ITEM'
  AND we_item.PROJECT_ID IS NULL
  AND p.WORK_EFFORT_TYPE_ID = 'PROJECT';

UPDATE WORK_EFFORT we_item
    INNER JOIN WORK_EFFORT p
    ON we_item.GlAccountId = p.GlAccountId
SET
    we_item.PROJECT_ID = p.WORK_EFFORT_ID,
    we_item.LAST_MODIFIED_DATE = CURRENT_TIMESTAMP,
    we_item.LAST_UPDATED_STAMP = CURRENT_TIMESTAMP
WHERE we_item.WORK_EFFORT_TYPE_ID = 'PAYMENT_CERTIFICATE_ITEM'
  AND we_item.PROJECT_ID IS NULL
  AND p.WORK_EFFORT_TYPE_ID = 'PROJECT'
  AND p.GlAccountId IS NOT NULL;