-- 1. ROLE_TYPE: Sales Manager
INSERT IGNORE INTO `ROLE_TYPE` (`ROLE_TYPE_ID`, `PARENT_TYPE_ID`, `HAS_TABLE`, `DESCRIPTION`, `CREATED_STAMP`, `LAST_UPDATED_STAMP`)
VALUES ('SALES_MANAGER', 'PERSON_ROLE', 'N', 'Sales Manager', NOW(), NOW());


-- 2. STATUS_TYPE: Commission Status (parent type for the statuses below)
INSERT IGNORE INTO `STATUS_TYPE` (`STATUS_TYPE_ID`, `PARENT_TYPE_ID`, `HAS_TABLE`, `DESCRIPTION`, `CREATED_STAMP`, `LAST_UPDATED_STAMP`)
VALUES ('COMMISSION_STATUS', NULL, 'N', 'Commission Status', NOW(), NOW());


-- 3. STATUS_ITEM: Commission statuses
INSERT IGNORE INTO `STATUS_ITEM` (`STATUS_ID`, `STATUS_TYPE_ID`, `STATUS_CODE`, `SEQUENCE_ID`, `DESCRIPTION`, `DESCRIPTION_ARABIC`, `CREATED_STAMP`, `LAST_UPDATED_STAMP`)
VALUES ('COMMISSION_PENDING', 'COMMISSION_STATUS', 'PENDING', '01', 'Pending', 'قيد الانتظار', NOW(), NOW());

INSERT IGNORE INTO `STATUS_ITEM` (`STATUS_ID`, `STATUS_TYPE_ID`, `STATUS_CODE`, `SEQUENCE_ID`, `DESCRIPTION`, `DESCRIPTION_ARABIC`, `CREATED_STAMP`, `LAST_UPDATED_STAMP`)
VALUES ('COMMISSION_APPROVED', 'COMMISSION_STATUS', 'APPROVED', '02', 'Approved', 'معتمدة', NOW(), NOW());

INSERT IGNORE INTO `STATUS_ITEM` (`STATUS_ID`, `STATUS_TYPE_ID`, `STATUS_CODE`, `SEQUENCE_ID`, `DESCRIPTION`, `DESCRIPTION_ARABIC`, `CREATED_STAMP`, `LAST_UPDATED_STAMP`)
VALUES ('COMMISSION_PAID', 'COMMISSION_STATUS', 'PAID', '03', 'Paid', 'مدفوعة', NOW(), NOW());
