SELECT
    p.*,
    g.ACCOUNT_NAME_ARABIC AS GlAccountName,
    g.PARENT_GL_ACCOUNT_ID,
    parent.ACCOUNT_NAME AS ParentAccountName
FROM PARTY_GL_ACCOUNT p
         JOIN GL_ACCOUNT g ON g.GL_ACCOUNT_ID = p.GL_ACCOUNT_ID
         LEFT JOIN GL_ACCOUNT parent ON parent.GL_ACCOUNT_ID = g.PARENT_GL_ACCOUNT_ID
WHERE  p.ROLE_TYPE_ID = 'BILL_FROM_VENDOR'
  AND g.PARENT_GL_ACCOUNT_ID = '250400';

DELETE p FROM PARTY_GL_ACCOUNT p
                  JOIN GL_ACCOUNT g ON g.GL_ACCOUNT_ID = p.GL_ACCOUNT_ID
WHERE 
  p.ROLE_TYPE_ID = 'BILL_FROM_VENDOR'
  AND g.PARENT_GL_ACCOUNT_ID = '250400';