-- =============================================================================
-- fix_subaccount_labels.sql
-- Purpose: make the manually-curated Sub-Account (Arabic) values durable at the
--          SOURCE, so the Dim_gl_account view (SUBACCOUNT / SUBACCOUNT_AR) returns
--          them automatically and Power BI can group/drill the generic
--          'Other Expenses' / 'Other Payables' / 'Other Receivables' matrix lines.
--
-- Source of truth for the intended values: 'GL_Account_Classification_Diagnostic
--          updated.xlsx' (accountant's curated Sub-Account (Arabic) column).
--
-- Lever: GL_ACCOUNT.GL_SUB_ACCOUNT_COURSE_LABEL_ID  (the sub-account drill level).
--        This does NOT change the ACCOUNT-level matrix line — only the drill under it.
--
-- Scope: 48 accounts.  5 reuse an existing label; 43 get new labels.
-- Idempotent: INSERT ... ON DUPLICATE KEY UPDATE + deterministic UPDATEs — safe to re-run.
--
-- NOTE (design): the 43 new labels are mostly genuine expense/deposit CATEGORIES
--   (bank fees, audit fees, transport, customer advances, short-term loans, per-project
--   operating expenses, ...). A few are account-specific proper nouns. New label IDs are
--   synthetic ('SUBACC_<account_id>') to guarantee uniqueness; the English DESCRIPTION
--   carries the account's English name where available. Adjust IDs/wording as you like.
-- NOT INCLUDED here (handled separately, not label fixes):
--   * 1201301 / 1201304 (مطعم السدة): you appended an operational note
--     'تم ربط الحساب 124620' — a working annotation, not a classification label.
--   * 321000 / 321100 / 321200 (جارى الشركاء): you blanked these; the real question
--     there is the ACCOUNT-level mapping to DIVIDENDS_PAID, separate from sub-accounts.
-- =============================================================================

START TRANSACTION;

-- ── 1. Reuse existing labels (Arabic already present in the dimension) ──────────
-- 'اعمال تحت التنفيذ للغير'  ->  existing label 'WIP Third Party'
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'WIP Third Party'
  WHERE GL_ACCOUNT_ID IN ('140701','140702','140703','140713','140723');

-- ── 2. Create new sub-account labels, then repoint their accounts ───────────────
-- (SORT_ORDER = account id so sub-accounts order naturally under their matrix line)
INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250120', 'CUSTOMER ADVANCES', 'دفعات مقدمة من العملاء', '250120')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250120'
  WHERE GL_ACCOUNT_ID IN ('250120');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250130', 'ACCRUED MAINTENANCE PAYABLE', 'ودائع صيانة العملاء', '250130')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250130'
  WHERE GL_ACCOUNT_ID IN ('250130');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250420', 'PROJECTS IN PROGRESS - SUNNY FARM', 'مزرعة السنية ذ.د', '250420')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250420'
  WHERE GL_ACCOUNT_ID IN ('250420');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250437', NULL, 'جدية حجز مشروع نسيم', '250437')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250437'
  WHERE GL_ACCOUNT_ID IN ('250437');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250452', NULL, 'قروض قصيرة الأجل', '250452')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250452'
  WHERE GL_ACCOUNT_ID IN ('250452');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250453', NULL, 'جدية حجز مشروع سوا', '250453')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250453'
  WHERE GL_ACCOUNT_ID IN ('250453');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250454', NULL, 'وليد البدرى - بيت الوطن لادريس التجمع', '250454')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250454'
  WHERE GL_ACCOUNT_ID IN ('250454');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250460', NULL, 'تريو ايه - شراء اسهم', '250460')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250460'
  WHERE GL_ACCOUNT_ID IN ('250460');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250510', NULL, 'حسام الدين مصطفى - شراء اسهم سيتى ووك', '250510')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250510'
  WHERE GL_ACCOUNT_ID IN ('250510');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250520', NULL, 'سكن الموظفين - الثالث زايد قطب مختار', '250520')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250520'
  WHERE GL_ACCOUNT_ID IN ('250520');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_250530', NULL, 'محمد عاكف - شراء سيتى ووك', '250530')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_250530'
  WHERE GL_ACCOUNT_ID IN ('250530');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600000', 'EXPENSE', 'المصروفات العمومية والإدارية', '600000')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600000'
  WHERE GL_ACCOUNT_ID IN ('600000');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600010', 'Financing Expenses', 'المصروفات التمويلية', '600010')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600010'
  WHERE GL_ACCOUNT_ID IN ('600010');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600012', 'OTHER FINANCING EXPENSES', 'مصاريف تمويلية أخرى', '600012')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600012'
  WHERE GL_ACCOUNT_ID IN ('600012');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600020', 'Operating Expenses', 'المصروفات التشغيلية', '600020')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600020'
  WHERE GL_ACCOUNT_ID IN ('600020');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600021', 'Operating Expenses - Golden Walk', 'المصروفات التشغيلية - جولدن ووك', '600021')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600021'
  WHERE GL_ACCOUNT_ID IN ('600021');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600022', 'Operating Expenses - Desert Mall', 'المصروفات التشغيلية - مول الصحراوى', '600022')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600022'
  WHERE GL_ACCOUNT_ID IN ('600022');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600023', 'Operating Expenses - City Walk', 'المصروفات التشغيلية - سيتى ووك', '600023')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600023'
  WHERE GL_ACCOUNT_ID IN ('600023');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600024', 'Operating Expenses - Naseem Project', 'المصروفات التشغيلية - مشروع نسيم', '600024')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600024'
  WHERE GL_ACCOUNT_ID IN ('600024');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600028', 'Desert Old Stable (2 Feddan) - Operating Exp', 'الاسطبل القديم الصحراوي 2 فدان - مصروفات تشغيلية', '600028')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600028'
  WHERE GL_ACCOUNT_ID IN ('600028');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600500', 'OFFICE SUPPLIES', 'الأدوات المكتبية', '600500')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600500'
  WHERE GL_ACCOUNT_ID IN ('600500');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600600', 'AUDIT FEES', 'أجور مراجعة الحسابات', '600600')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600600'
  WHERE GL_ACCOUNT_ID IN ('600600');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600700', 'TRANSPORTATION & TRAVEL', 'النقل والمواصلات', '600700')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600700'
  WHERE GL_ACCOUNT_ID IN ('600700');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600800', 'MAINTENANCE & REPAIRS', 'الصيانة والإصلاح', '600800')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600800'
  WHERE GL_ACCOUNT_ID IN ('600800');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600900', 'Cleaning Supplies', 'أدوات النظافة', '600900')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600900'
  WHERE GL_ACCOUNT_ID IN ('600900');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600940', 'Bank Fees', 'رسوم بنكية', '600940')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600940'
  WHERE GL_ACCOUNT_ID IN ('600940');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600950', 'Computer Supplies', 'لوازم كمبيوتر', '600950')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600950'
  WHERE GL_ACCOUNT_ID IN ('600950');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600960', 'Photo Copier Supplies', 'لوازم ماكينة التصوير', '600960')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600960'
  WHERE GL_ACCOUNT_ID IN ('600960');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600980', 'Public Relations and Buffet', 'مصاريف بوفيه و ضيافة', '600980')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600980'
  WHERE GL_ACCOUNT_ID IN ('600980');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_600990', 'Governmintal Fees', 'رسوم وتراخيص حكومية', '600990')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_600990'
  WHERE GL_ACCOUNT_ID IN ('600990');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601210', 'Car registration renewal fees', 'رسوم تجديد وتراخيص سيارات', '601210')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601210'
  WHERE GL_ACCOUNT_ID IN ('601210');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601220', 'Shipping Charges', 'رسوم بريدية وشحن', '601220')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601220'
  WHERE GL_ACCOUNT_ID IN ('601220');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601230', 'Medical Charges', 'مصاريف طبية ودوائية', '601230')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601230'
  WHERE GL_ACCOUNT_ID IN ('601230');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601240', 'Legal and Consulting Expenses', 'مصاريف قانونية واستشارية', '601240')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601240'
  WHERE GL_ACCOUNT_ID IN ('601240');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601250', 'Miscilenious Expenses', 'مصاريف متنوعة', '601250')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601250'
  WHERE GL_ACCOUNT_ID IN ('601250');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601260', 'General Insurance', 'تأمينات متنوعة', '601260')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601260'
  WHERE GL_ACCOUNT_ID IN ('601260');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601270', 'Advertising Expenses', 'مصاريف دعاية وإعلان', '601270')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601270'
  WHERE GL_ACCOUNT_ID IN ('601270');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_601280', 'Software Expenses', 'مصاريف برامج وأنظمة', '601280')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_601280'
  WHERE GL_ACCOUNT_ID IN ('601280');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_830000', 'Hospitality and PR Expenses', 'مصاريف ضيافة و علاقات عامة', '830000')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_830000'
  WHERE GL_ACCOUNT_ID IN ('830000');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_870000', 'Golden Co - Exterior Facade Cleaning', 'تنظيف الواجهات الخارجية شركة جولدن', '870000')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_870000'
  WHERE GL_ACCOUNT_ID IN ('870000');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_890000', 'Internal Corporate Printing', 'مطبوعات داخلية', '890000')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_890000'
  WHERE GL_ACCOUNT_ID IN ('890000');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_910000', 'Ramadan Meals and Charity Boxes', 'رمضان افطار وجبات كراتين', '910000')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_910000'
  WHERE GL_ACCOUNT_ID IN ('910000');

INSERT INTO GL_SUB_ACCOUNT_COURSE_LABEL
  (GL_SUB_ACCOUNT_COURSE_LABEL_ID, DESCRIPTION, DESCRIPTION_ARABIC, SORT_ORDER)
  VALUES ('SUBACC_920000', NULL, 'اجهزة لاب توب و طابعات', '920000')
  ON DUPLICATE KEY UPDATE DESCRIPTION=VALUES(DESCRIPTION),
    DESCRIPTION_ARABIC=VALUES(DESCRIPTION_ARABIC), SORT_ORDER=VALUES(SORT_ORDER);
UPDATE GL_ACCOUNT SET GL_SUB_ACCOUNT_COURSE_LABEL_ID = 'SUBACC_920000'
  WHERE GL_ACCOUNT_ID IN ('920000');

COMMIT;

-- ── Verification (run after commit) ─────────────────────────────────────────────
SELECT d.GL_ACCOUNT_ID, d.ACCOUNT_NAME_ARABIC, d.ACCOUNT AS matrix_line,
       d.SUBACCOUNT, d.SUBACCOUNT_AR
FROM Dim_gl_account d
WHERE d.GL_ACCOUNT_ID IN ('140701','140702','140703','140713','140723','250120','250130','250420','250437','250452','250453','250454','250460','250510','250520','250530','600000','600010','600012','600020','600021','600022','600023','600024','600028','600500','600600','600700','600800','600900','600940','600950','600960','600980','600990','601210','601220','601230','601240','601250','601260','601270','601280','830000','870000','890000','910000','920000')
ORDER BY d.ACCOUNT_SORT, d.SUBACCOUNT_SORT;
