-- =============================================================
-- PATCH: GL_ACCOUNT classifier update for records where
-- GL_ACCOUNT_TYPE_ID IS NULL — matched on GL_ACCOUNT_CLASS_ID only
-- Run this AFTER the main update script
-- =============================================================

UPDATE GL_ACCOUNT SET
    GL_REPORT_ID = CASE
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_AMORTIZATION' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_DEPRECIATION' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'AMORTIZATION' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'ASSET' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EQUIVALENT' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EXPENSE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_INCOME' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'COGS_EXPENSE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_ASSET' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_REVENUE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CREDIT' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_ASSET' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_LIABILITY' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEBIT' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEPRECIATION' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'DISTRIBUTION' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'DIVIDEND' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'EQUITY' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'EXPENSE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'INCOME' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'INTEREST_EXPENSE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ADJUST' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ASSET' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'LIABILITY' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_ASSET' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_LIABILITY' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_EXPENSE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_INCOME' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_POSTING' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'OWNERS_EQUITY' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'RESOURCE' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETAINED_EARNINGS' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETURN_OF_CAPITAL' THEN 'BALANCE_SHEET'
        WHEN GL_ACCOUNT_CLASS_ID = 'REVENUE' THEN 'PROFIT_AND_LOSS'
        WHEN GL_ACCOUNT_CLASS_ID = 'SGA_EXPENSE' THEN 'PROFIT_AND_LOSS'
        ELSE GL_REPORT_ID
    END,

    GL_CLASS_COURSE_ID = CASE
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_AMORTIZATION' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_DEPRECIATION' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'AMORTIZATION' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EQUIVALENT' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EXPENSE' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_INCOME' THEN 'NON_OPERATING'
        WHEN GL_ACCOUNT_CLASS_ID = 'COGS_EXPENSE' THEN 'TRADING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_REVENUE' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_LIABILITY' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEPRECIATION' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'DISTRIBUTION' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'DIVIDEND' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'EQUITY' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'EXPENSE' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'INCOME' THEN 'NON_OPERATING'
        WHEN GL_ACCOUNT_CLASS_ID = 'INTEREST_EXPENSE' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ADJUST' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'LIABILITY' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_LIABILITY' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_EXPENSE' THEN 'OPERATING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_INCOME' THEN 'NON_OPERATING'
        WHEN GL_ACCOUNT_CLASS_ID = 'OWNERS_EQUITY' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETAINED_EARNINGS' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETURN_OF_CAPITAL' THEN 'LIABILITIES_AND_OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'REVENUE' THEN 'TRADING_ACCOUNT'
        WHEN GL_ACCOUNT_CLASS_ID = 'SGA_EXPENSE' THEN 'OPERATING_ACCOUNT'
        ELSE GL_CLASS_COURSE_ID
    END,

    GL_SUB_CLASS_ID = CASE
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_AMORTIZATION' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_DEPRECIATION' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'AMORTIZATION' THEN 'DEPRECIATION_AND_AMORTIZATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EQUIVALENT' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EXPENSE' THEN 'OPERATING_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'COGS_EXPENSE' THEN 'COST_OF_SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_REVENUE' THEN 'SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_LIABILITY' THEN 'LIABILITIES'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEPRECIATION' THEN 'DEPRECIATION_AND_AMORTIZATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'DISTRIBUTION' THEN 'OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'DIVIDEND' THEN 'OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'EQUITY' THEN 'OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'EXPENSE' THEN 'OPERATING_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'INTEREST_EXPENSE' THEN 'OPERATING_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ADJUST' THEN 'DEPRECIATION_AND_AMORTIZATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'LIABILITY' THEN 'LIABILITIES'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_ASSET' THEN 'ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_LIABILITY' THEN 'LIABILITIES'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_EXPENSE' THEN 'OPERATING_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'OWNERS_EQUITY' THEN 'OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETAINED_EARNINGS' THEN 'OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETURN_OF_CAPITAL' THEN 'OWNERS_EQUITY'
        WHEN GL_ACCOUNT_CLASS_ID = 'REVENUE' THEN 'SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'SGA_EXPENSE' THEN 'OPERATING_EXPENSES'
        ELSE GL_SUB_CLASS_ID
    END,

    GL_SUB_CLASS_2_ID = CASE
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_AMORTIZATION' THEN 'NON_CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_DEPRECIATION' THEN 'NON_CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'AMORTIZATION' THEN 'AMORTIZATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'ASSET' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EQUIVALENT' THEN 'CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EXPENSE' THEN 'ADMINISTRATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'COGS_EXPENSE' THEN 'COST_OF_SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_ASSET' THEN 'NON_CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_REVENUE' THEN 'SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CREDIT' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_ASSET' THEN 'CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_LIABILITY' THEN 'CURRENT_LIABILITIES'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEBIT' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEPRECIATION' THEN 'DEPRECIATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'DISTRIBUTION' THEN 'RETAINED_EARNINGS'
        WHEN GL_ACCOUNT_CLASS_ID = 'DIVIDEND' THEN 'RETAINED_EARNINGS'
        WHEN GL_ACCOUNT_CLASS_ID = 'EQUITY' THEN 'SHARE_CAPITAL'
        WHEN GL_ACCOUNT_CLASS_ID = 'EXPENSE' THEN 'ADMINISTRATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'INTEREST_EXPENSE' THEN 'INTEREST_EXPENSE'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ADJUST' THEN 'ADMINISTRATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ASSET' THEN 'CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'LIABILITY' THEN 'CURRENT_LIABILITIES'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_ASSET' THEN 'NON_CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_LIABILITY' THEN 'LONG_TERM_LIABILITIES'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_EXPENSE' THEN 'ADMINISTRATION'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_POSTING' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'OWNERS_EQUITY' THEN 'SHARE_CAPITAL'
        WHEN GL_ACCOUNT_CLASS_ID = 'RESOURCE' THEN 'ADJUSTING'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETAINED_EARNINGS' THEN 'RETAINED_EARNINGS'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETURN_OF_CAPITAL' THEN 'RETAINED_EARNINGS'
        WHEN GL_ACCOUNT_CLASS_ID = 'REVENUE' THEN 'SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'SGA_EXPENSE' THEN 'ADMINISTRATION'
        ELSE GL_SUB_CLASS_2_ID
    END,

    GL_ACCOUNT_COURSE_LABEL_ID = CASE
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_AMORTIZATION' THEN 'AMORTIZATION_OF_INTANGIBLE_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'ACCUM_DEPRECIATION' THEN 'EQUIPMENT'
        WHEN GL_ACCOUNT_CLASS_ID = 'AMORTIZATION' THEN 'AMORTIZATION_OF_INTANGIBLE_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'ASSET' THEN 'OTHER_CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EQUIVALENT' THEN 'CASH_AND_CASH_EQUIVALENTS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_EXPENSE' THEN 'OTHER_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CASH_INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'COGS_EXPENSE' THEN 'COST_OF_SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_ASSET' THEN 'PROPERTY_PLANT_AND_EQUIPMENT'
        WHEN GL_ACCOUNT_CLASS_ID = 'CONTRA_REVENUE' THEN 'SALES_RETURN'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_ASSET' THEN 'OTHER_CURRENT_ASSETS'
        WHEN GL_ACCOUNT_CLASS_ID = 'CURRENT_LIABILITY' THEN 'OTHER_PAYABLES'
        WHEN GL_ACCOUNT_CLASS_ID = 'DEPRECIATION' THEN 'EQUIPMENT'
        WHEN GL_ACCOUNT_CLASS_ID = 'DISTRIBUTION' THEN 'DIVIDENDS_PAID'
        WHEN GL_ACCOUNT_CLASS_ID = 'DIVIDEND' THEN 'DIVIDENDS_PAID'
        WHEN GL_ACCOUNT_CLASS_ID = 'EQUITY' THEN 'SHARE_CAPITAL'
        WHEN GL_ACCOUNT_CLASS_ID = 'EXPENSE' THEN 'OTHER_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'INTEREST_EXPENSE' THEN 'INTEREST_EXPENSE'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ADJUST' THEN 'COST_OF_SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'INVENTORY_ASSET' THEN 'INVENTORY'
        WHEN GL_ACCOUNT_CLASS_ID = 'LIABILITY' THEN 'OTHER_PAYABLES'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_ASSET' THEN 'PROPERTY_PLANT_AND_EQUIPMENT'
        WHEN GL_ACCOUNT_CLASS_ID = 'LONGTERM_LIABILITY' THEN 'LONG_TERM_OBLIGATIONS'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_EXPENSE' THEN 'OTHER_EXPENSES'
        WHEN GL_ACCOUNT_CLASS_ID = 'NON_CASH_INCOME' THEN 'DIVIDEND_INCOME'
        WHEN GL_ACCOUNT_CLASS_ID = 'OWNERS_EQUITY' THEN 'SHARE_CAPITAL'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETAINED_EARNINGS' THEN 'RETAINED_EARNINGS'
        WHEN GL_ACCOUNT_CLASS_ID = 'RETURN_OF_CAPITAL' THEN 'DIVIDENDS_PAID'
        WHEN GL_ACCOUNT_CLASS_ID = 'REVENUE' THEN 'SALES'
        WHEN GL_ACCOUNT_CLASS_ID = 'SGA_EXPENSE' THEN 'OTHER_EXPENSES'
        ELSE GL_ACCOUNT_COURSE_LABEL_ID
    END

WHERE GL_ACCOUNT_TYPE_ID IS NULL
  AND GL_ACCOUNT_CLASS_ID IS NOT NULL;

UPDATE GL_ACCOUNT child
    JOIN GL_ACCOUNT parent
    ON child.PARENT_GL_ACCOUNT_ID = parent.GL_ACCOUNT_ID
SET
    child.GL_REPORT_ID               = parent.GL_REPORT_ID,
    child.GL_CLASS_COURSE_ID         = parent.GL_CLASS_COURSE_ID,
    child.GL_SUB_CLASS_ID            = parent.GL_SUB_CLASS_ID,
    child.GL_SUB_CLASS_2_ID          = parent.GL_SUB_CLASS_2_ID,
    child.GL_ACCOUNT_COURSE_LABEL_ID = parent.GL_ACCOUNT_COURSE_LABEL_ID
WHERE
    child.GL_REPORT_ID IS NULL
  AND parent.GL_REPORT_ID IS NOT NULL;

SELECT
    GL_ACCOUNT_ID,
    GL_ACCOUNT_CLASS_ID,
    GL_ACCOUNT_TYPE_ID,
    PARENT_GL_ACCOUNT_ID,
    ACCOUNT_NAME,
    ACCOUNT_NAME_ARABIC,
    GL_REPORT_ID,
    GL_CLASS_COURSE_ID,
    GL_SUB_CLASS_ID,
    GL_SUB_CLASS_2_ID,
    GL_ACCOUNT_COURSE_LABEL_ID
FROM GL_ACCOUNT
WHERE GL_REPORT_ID IS NULL
ORDER BY PARENT_GL_ACCOUNT_ID, GL_ACCOUNT_ID;